#!/usr/bin/env php
<?php declare(strict_types=1);

use PhpyReqsHelper\Application;
use PhpyReqsHelper\Commands\catchCommand;
use PhpyReqsHelper\Commands\InstallCommand;

require_once __DIR__ . '/vendor/autoload.php';

$application = new Application();

$application->addCommands([
    new InstallCommand(),
    new catchCommand(),

]);
try {
    $application->run();
} catch (Exception $e) {
    exit($e->getMessage() . PHP_EOL);
}