"""
This file is auto-generated by phpy. Please do not modify it.
"""

import pyorc.converters



class workbunny_phporc_converters_decimalconverterclass(pyorc.converters.DecimalConverter):
  def __init__(self, _this):
    self.__this = _this
    _this.set('_super', super())
    _this.set('_self', self)
    _this.call('__init')

  def from_orc(self, args):
    return self.__this.call('from_orc', args)

  def to_orc(self, args):
    return self.__this.call('to_orc', args)

  def __init(self, ):
    return self.__this.call('__init', )

